name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache git zip unzip openjdk-17-jdk python3-pip
          pip install buildozer cython==0.29.36

      - name: 📦 Install Android SDK command line tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0" "platforms;android-34" "platform-tools"

      - name: 🛠️ Build APK
        run: buildozer android debug

      - name: 📤 Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: talka-apk
          path: bin/*.apk
