name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache git unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: 📦 Install Android SDK & Accept Licenses
        run: |
          mkdir -p $HOME/.android && echo "### User Sources for Android SDK Manager" > $HOME/.android/repositories.cfg
          yes | sdkmanager --licenses || true
          sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"

      - name: 🛠️ Build APK
        run: |
          buildozer android debug

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: talka-apk
          path: bin/*.apk
        
